{
 "title": "App monitoring staging",
 "tags": [
  "staging",
  "app"
 ],
 "time": { "from": "2024-10-23T21:44:43.527Z", "to": "2024-10-23T22:00:36.763Z" },
 "templating": {
  "list": [
   {
    "name": "the_job",
    "query": "\"staging-ns/web-app\""
   },
   {
    "name": "the_job_app",
    "query": "{job=\"staging-ns/web-app\", app=\"web-app\"}"
   },
   {
    "name": "the_app",
    "query": "\"web-app\""
   }
  ]
 },
 "panels": [
  {
   "title": "INFO responses counter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time($the_job_app | json | level=\"INFO\" | django_url_path !=\"\" | status_code!=\"no status code\" | __error__=\"\" [${__range_s}s]))\n"
    }
   ]
  },
  {
   "title": "ERROR responses counter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time($the_job_app | json | level=\"ERROR\" | django_url_path != \"\" | status_code!=\"no status code\" | __error__=\"\" [${__range_s}s]))\n"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (count_over_time($the_job_app | json | status_code!=\"\" | status_code!=\"no status code\" [${__range_s}s]))\n\n",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "ERROR/INFO %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(count_over_time($the_job_app | json | level=\"ERROR\" | django_url_path!=\"\" | __error__=\"\" [${__range_s}s]))/ sum(count_over_time($the_job_app | json | level=\"INFO\" | django_url_path!=\"\" | __error__=\"\" [${__range_s}s])) * 100\n\n"
    }
   ]
  },
  {
   "title": "Response timings(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(\n  $the_job_app\n  | json\n  | response_time != \"\"\n  | django_url_path != \"\"\n  | status_code != \"\"\n  |  __error__=\"\" \n  | unwrap response_time [${__range_s}s]\n) by (django_url_path)",
     "legendFormat": "{{django_url_path}}"
    }
   ]
  },
  {
   "title": "User counter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (sum by (user_id) (count_over_time($the_job_app | json | __error__=\"\" [${__range_s}s]   )))\n",
     "legendFormat": "{{user_id}}"
    }
   ]
  },
  {
   "title": "Failing endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (django_url_path) (count_over_time({app=\"web-app\"} \n| json \n| level = \"ERROR\" \n| django_url_path!=\"\"\n| __error__=\"\" [${__range_s}s])\n )",
     "legendFormat": "{{django_url_path}}"
    }
   ]
  },
  {
   "title": "Shop Locations",
   "type": "geomap",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,\n  ST_Y(coordinates) AS latitude,\n  ST_X(coordinates) AS longitude\nfrom\n  shops"
    }
   ]
  }
 ]
}