{
 "title": "Staging app monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Response timings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (url) \n(\n  avg_over_time\n(\n  {job=\"staging-ns/api-deployment\"}\n  | json\n  | __error__!=\"JSONParserErr\"\n  | __error__=\"\"\n  | event=\"finished\"\n  | unwrap process_time_ms\n  [${__range_s}s]\n) \n)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "INFO responses counter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {job=\"staging-ns/api-deployment\"}\n    | json\n    | __error__!=\"JSONParserErr\"\n    | level=\"INFO\"\n    | event=\"finished\"\n    [${__range_s}s]\n  )\n)"
    }
   ]
  },
  {
   "title": "ERROR responses counter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {job=\"staging-ns/api-deployment\"}\n    | json\n    | __error__!=\"JSONParserErr\"\n    | level=\"ERROR\"\n    | event=\"finished\"\n    [${__range_s}s]\n  )\n)"
    }
   ]
  },
  {
   "title": "ERROR/INFO %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  count_over_time(\n    {job=\"staging-ns/api-deployment\"} \n    | json\n    | __error__!=\"JSONParserErr\"\n    | level=\"ERROR\"\n     [${__range_s}s]\n  )\n)\n/\nsum(\n  count_over_time(\n    {job=\"staging-ns/api-deployment\"} \n    | json \n    | __error__!=\"JSONParserErr\"\n    | level=\"INFO\"\n     [${__range_s}s]\n  )\n)\n* 100",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Failing endpoints",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url) \n(count_over_time(\n  {job=\"staging-ns/api-deployment\"} \n  | json \n  | __error__!=\"JSONParserErr\"\n  | level = \"ERROR\" \n  | url!=\"\"\n [${__range_s}s])\n )",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (\n  count_over_time({job=\"staging-ns/api-deployment\"} \n  | json\n  | __error__!=\"JSONParserErr\"\n  | status_code != \"\"\n  [${__range_s}s]\n  )\n)",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}